storage:
  connection-string: ""
  container: "february"

search:
  service-name: "wbsearchtest"
  api-version: "2020-06-30"
  api-key: ""
  index-name:  "february"

files:
  download-blob-directory: "files/blob-files"
  processed-directory: "files/processed"
  ingested-file: "ingested.txt"
  failed-to-ingest-file: "failed-to-ingest.txt"

parser:
  milliseconds-interval: 10000
